# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_table <- function(x, size = 5L) {
    .Call(`_rlas_fast_table`, x, size)
}

fast_countequal <- function(x, t) {
    .Call(`_rlas_fast_countequal`, x, t)
}

fast_countbelow <- function(x, t) {
    .Call(`_rlas_fast_countbelow`, x, t)
}

fast_countover <- function(x, t) {
    .Call(`_rlas_fast_countover`, x, t)
}

C_reader <- function(ifiles, ofile, select, filter, filter_wkt) {
    .Call(`_rlas_C_reader`, ifiles, ofile, select, filter, filter_wkt)
}

lasheaderreader <- function(file) {
    .Call(`_rlas_lasheaderreader`, file)
}

lasfilterusage <- function() {
    invisible(.Call(`_rlas_lasfilterusage`))
}

C_writer <- function(file, LASheader, data) {
    invisible(.Call(`_rlas_C_writer`, file, LASheader, data))
}

laxwriter <- function(file, verbose) {
    invisible(.Call(`_rlas_laxwriter`, file, verbose))
}

